# Site settings
title: Blog
description: My blog for PowerShell, IT Managment and hope for DevOps
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://jonjunell.github.io/" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
twitter: jonhikes
github:  jonjunell

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
# analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate
  
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
